new openshift

diff --git a/.openshift/action_hooks/deploy b/.openshift/action_hooks/deploy
--- a/.openshift/action_hooks/deploy
+++ b/.openshift/action_hooks/deploy
@@ -1,7 +1,25 @@
-export SECRET_TOKEN=49ec79cf6a8fe9fd506352d68add508a3368de9ab50771f6d4ce0341d977f4dd8170c23062ea27ad29662d617a57317b3c04916370508cb789dd247bb10d6b34
+#!/bin/bash
+# This deploy hook gets executed after dependencies are resolved and the
+# build hook has been run but before the application has been started back
+# up again.  This script gets executed directly, so it could be python, php,
+# ruby, etc.
+
+set -e
+
+if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
+then
+    echo 1>&2
+    echo "Could not find mysql database.  Please run:" 1>&2
+    echo "rhc cartridge add -a $OPENSHIFT_APP_NAME -c mysql-5.1" 1>&2
+    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
+    echo 1>&2
+fi
+
+if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
+then
+    exit 5
+fi
 
 pushd ${OPENSHIFT_REPO_DIR} > /dev/null
-
 bundle exec rake db:migrate RAILS_ENV="production"
-
 popd > /dev/null
